### PR TITLE
feat(dx): add .nvmrc

### PR DESCRIPTION
**Pull request by spg**
`.nvmrc` is useful when using `nvm`. When a `.nvmrc` file is detected in the current working directory, `nvm` will use the Node version specified in the `.nvmrc` file.

### CODE REVIEW

**Review by laurentlp — COMMENTED** [review]
Not sure if the code is compatible with NodeJS 16. We would have to test the build, tests, and binaries first!

**Comment by spg** [comment]
What's the current version of Node you're supporting?

**Comment by samuelmasse** [comment]
@spg If you look at the git changes we already had a .nvmrc with 12.18.3 in it

**Comment by spg** [comment]
Oh yeah sorry, my bad

**Pull request closed without merging**
