### PR TITLE
fix(smooch): strip markdown from messages to whatsapp

### PR DESCRIPTION
**Pull request by charlescatta**
Cleans markdown messages into clean text messages over channel-smooch

Fixes https://linear.app/botpress/issue/DEV-1887/[bug]-markdown-incompatible-with-whatsapp-botpressborpress-5544

### CODE REVIEW

**Comment by samuelmasse** [comment]
This removes all markdown sent to smooch, not just to whatsapp

**Comment by charlescatta** [comment]
yes absolutely. The bug report did refer to whats app through smooch, not sure if detection is possible due to the nature of smooch

**Comment by charlescatta** [comment]
@samuelmasse do any of the downstream smooch channels support botpress's markdown except for slack?

**Comment by samuelmasse** [comment]
@charlescatta I believe telegram does

**Comment by samuelmasse** [comment]
@charlescatta We'll close this PR for now. We might reopen if we decide to completely remove markdown for the smooch channel. In my opinion this more a problem on smooch's side. Smooch has released a v2 version of their apis that we migth want to upgrade to. It could solve this problem.

**Pull request closed without merging**
