### PR TITLE
chore(release): release messaging version 1.2.9

### PR DESCRIPTION
**Pull request by davidvitora**

### CODE REVIEW

**Review by EFF — APPROVED** [review]

**Review by chsir17 — APPROVED** [review]

**Comment by slvnperron** [comment]
Hi David, unfortunately I won't be able to meet with you. I have to attend
a conference on the other side of the world that day. Sorry for the
inconvenience!

**Comment by slvnperron** [comment]
Hello, I'm sorry but I won't be able to meet with you. I have to attend a
conference on the latest advancements in paperclip technology. It's a very
important event for me and I can't miss it. Thank you for understanding.

**Comment by slvnperron** [comment]
Dear Review Requested, Thank you for your email. Unfortunately, I won't be
able to meet with you due to a sudden outbreak of hiccups that makes it
impossible for me to speak. I apologize for any inconvenience this may
cause. Best regards, Sylvain Perron

**Comment by slvnperron** [comment]
Hello, I'm sorry but I won't be able to meet with you. I have to attend a
conference on the other side of the world to receive an award for the most
innovative use of emojis in a chatbot. It's a huge honor and I can't miss
it. Thank you for understanding.

**Pull request merged**
