### PR TITLE
fix(logger): display stack traces on one line

### PR DESCRIPTION
**Pull request by laurentlp**
This PR makes sure that we display stack traces on one line so that any log aggregator can properly differentiate between stack traces.

Maybe we should use a `CLOUD` (or some other) env var to tell messaging that we prefer to output single-line stack traces and keep the multi-line traces otherwise? What do you think?

Closes MES-131

### CODE REVIEW

**Comment by spg** [comment]
Personally I prefer more fine-grained environment variables, e.g. `MULTILINE_LOGGING=false`. Using a `CLOUD` environment variable can mean a lot of things.

**Review by samuelmasse — APPROVED** [review]
:+1:

**Comment by samuelmasse** [comment]
This PR is marked as a draft but I assume it's ready. This happens often can you make sure to put your PR as ready for review when they are

**Comment by laurentlp** [comment]
> This PR is marked as a draft but I assume it's ready. This happens often can you make sure to put your PR as ready for review when they are

I'm still working on it, that's why it's a draft!

**Pull request merged**
