### PR TITLE
fix(messaging): fix inject error

### PR DESCRIPTION
**Pull request by allardy**
Pretty sure the error is related to the "isWebchatEvent" function... It was really too basic.
image

These event causes those errors:
image

Still need a way to test them correctly, since stratus uses the CDN, I didn't test "strictly", but logic looks fine.

### CODE REVIEW

**Comment by allardy** [comment]
https://linear.app/botpress/issue/STU-44/fix-annoying-error-coming-injectts

**Comment by spg** [comment]
Adding tests for that function would be pretty easy. Should we do this now?

**Comment by allardy** [comment]
Agreed that tests would be nice, but i'm not really used to DOM testing. Could be a good challenge for someone who implements new features in the future

**Comment by allardy** [comment]
@spg Tests added.

I disabled the firefox test because it's broken and has been for a long time, 6h running time is abusive. Fixing the real error should be done in a sepatate pr

image
image

**Comment by spg** [comment]
@allardy please add a ticket in Linear so we remember to fix the tests

**Review by spg — APPROVED** [review]

**Pull request merged**
